nunh = int(input("Digites um numero para ver sua tabuada: "))
print("_" *12)
print("{} x {:2} = {}" .format(nunh, 1, nunh*1))
print("{} x {:2} = {}" .format(nunh, 2, nunh*2))
print("{} x {:2} = {}" .format(nunh, 3, nunh*3))
print("{} x {:2} = {}" .format(nunh, 4, nunh*4))
print("{} x {:2} = {}" .format(nunh, 5, nunh*5))
print("{} x {:2} = {}" .format(nunh, 6, nunh*6))
print("{} x {:2} = {}" .format(nunh, 7, nunh*7))
print("{} x {:2} = {}" .format(nunh, 8, nunh*8))
print("{} x {:2} = {}" .format(nunh, 9, nunh*9))
print("{} x {:2} = {}" .format(nunh, 10, nunh*10))
print("_"*12)